# MongoDB Atlas connection
spring.data.mongodb.uri={MONGO_URI}

# Server configuration
server.port={SERVER_PORT}

# Cache configuration
spring.cache.type=simple

# Custom configuration
url-shortener.allowed-characters=0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
url-shortener.key-length=7
url-shortener.base-url=http://localhost:8080/
