package com.tinyurl.entity;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

/**
 * MongoDB entity representing a shortened URL mapping.
 *
 * <p>This entity stores the complete information for a URL shortening operation,
 * including the original URL, its shortened alias, creation metadata, and access
 * analytics. The entity is designed for efficient storage and retrieval in MongoDB
 * with appropriate indexing and validation constraints.</p>
 *
 * <p>The entity supports MongoDB's auditing features for automatic timestamp
 * management and optimistic locking through versioning. It follows best practices
 * for MongoDB document design with proper field validation and indexing strategies.</p>
 *
 * <p><strong>MongoDB Collection:</strong> urls</p>
 *
 * <p><strong>Key Features:</strong></p>
 * <ul>
 *   <li>Automatic timestamp management via {@link CreatedDate}</li>
 *   <li>Optimistic locking support through {@link Version}</li>
 *   <li>Unique constraint on alias field for collision prevention</li>
 *   <li>Built-in validation with Jakarta Bean Validation</li>
 *   <li>Efficient querying through strategic indexing</li>
 * </ul>
 *
 * @author Jose
 * @since 1.0
 * @see org.springframework.data.mongodb.core.mapping.Document
 * @see org.springframework.data.annotation.CreatedDate
 * @see org.springframework.data.annotation.Version
 */
@Document(collection = "urls")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UrlEntity {

    /**
     * Unique identifier for the MongoDB document.
     *
     * <p>This field serves as the primary key for the MongoDB document and is
     * automatically generated by MongoDB using ObjectId when not explicitly set.
     * The {@link Id} annotation designates this field as the document identifier.</p>
     *
     * <p><strong>Type:</strong> String representation of MongoDB ObjectId</p>
     * <p><strong>Generation:</strong> Automatic by MongoDB if not provided</p>
     * <p><strong>Example:</strong> "507f1f77bcf86cd799439011"</p>
     */
    @Id
    private String id;

    /**
     * The original long URL that was shortened.
     *
     * <p>This field stores the complete destination URL where users will be
     * redirected when accessing the shortened URL. It must be a valid, non-blank
     * URL that follows proper URL format conventions.</p>
     *
     * <p><strong>Validation:</strong> Cannot be null, empty, or contain only whitespace.
     * Additional URL format validation should be performed at the service layer.</p>
     *
     * <p><strong>Storage Considerations:</strong> URLs can be lengthy, but MongoDB
     * handles variable-length strings efficiently. Consider URL length limits
     * based on browser and server constraints (typically 2048 characters).</p>
     *
     * <p><strong>Example:</strong> "<a href="https://www.example.com/articles/spring-boot-mongodb-tutorial">...</a>"</p>
     */
    @NotBlank
    private String originalUrl;

    /**
     * The unique alias or short code for the URL.
     *
     * <p>This field contains the unique identifier used in the shortened URL path.
     * It can be either a custom alias provided by users or an automatically generated
     * short code. The field is indexed with a unique constraint to ensure no
     * duplicate aliases exist in the system.</p>
     *
     * <p><strong>Uniqueness:</strong> Enforced at the database level via unique index.
     * Duplicate alias insertion attempts will result in MongoDB duplicate key errors.</p>
     *
     * <p><strong>Index Performance:</strong> The unique index enables efficient
     * lookups during redirection operations, which are the most frequent database
     * operations in a URL shortening service.</p>
     *
     * <p><strong>Character Constraints:</strong> While not enforced at the entity level,
     * the service layer should restrict this to URL-safe characters (a-zA-Z0-9_-)</p>
     *
     * <p><strong>Examples:</strong></p>
     * <ul>
     *   <li>Custom alias: "my-blog-post"</li>
     *   <li>Generated code: "a1B2c3D"</li>
     * </ul>
     */
    @Indexed(unique = true)
    private String alias;

    /**
     * Timestamp when the URL was first created.
     *
     * <p>This field is automatically populated by Spring Data MongoDB's auditing
     * feature when the document is first saved. The {@link CreatedDate} annotation
     * ensures this field is set only once during document creation and remains
     * immutable thereafter.</p>
     *
     * <p><strong>Auditing Requirement:</strong> Requires {@code @EnableMongoAuditing}
     * to be configured in the application for automatic population.</p>
     *
     * <p><strong>Timezone Handling:</strong> Stored in the database timezone (typically UTC).
     * Application layer should handle timezone conversion for display purposes.</p>
     *
     * <p><strong>Immutability:</strong> This field is set once during creation and
     * should not be modified in subsequent updates.</p>
     *
     * <p><strong>Usage:</strong> Essential for analytics, audit trails, and
     * understanding URL creation patterns over time.</p>
     */
    @CreatedDate
    private Date createdDate;

    /**
     * Counter for the number of times this URL has been accessed.
     *
     * <p>This field tracks access analytics by counting successful redirections
     * to the original URL. Each time a user accesses the shortened URL and gets
     * successfully redirected, this counter is incremented.</p>
     *
     * <p><strong>Initial Value:</strong> Set to 0L when the URL is first created,
     * ensuring new URLs start with a zero click count.</p>
     *
     * <p><strong>Data Type:</strong> Uses {@code Long} to accommodate high-traffic
     * URLs that may exceed {@code Integer.MAX_VALUE} (2.1 billion) over time.</p>
     *
     * <p><strong>Concurrency Considerations:</strong> In high-traffic scenarios,
     * consider using atomic increment operations or eventual consistency patterns
     * to handle concurrent updates without performance degradation.</p>
     *
     * <p><strong>Analytics Value:</strong> Provides immediate insights into URL
     * popularity, campaign effectiveness, and user engagement patterns.</p>
     */
    private Long clickCount = 0L;

    /**
     * Version field for optimistic locking support.
     *
     * <p>This field enables optimistic concurrency control to prevent lost updates
     * when multiple processes attempt to modify the same document simultaneously.
     * Spring Data MongoDB automatically increments this field on each update operation.</p>
     *
     * <p><strong>Optimistic Locking:</strong> When updating a document, the version
     * is checked to ensure it matches the expected value. If the version has changed
     * (indicating another process modified the document), an {@code OptimisticLockingFailureException}
     * is thrown.</p>
     *
     * <p><strong>Automatic Management:</strong> Spring Data MongoDB handles version
     * increment automatically during save operations, requiring no manual intervention.</p>
     *
     * <p><strong>Concurrency Safety:</strong> Essential for maintaining data integrity
     * in scenarios where multiple services or users might modify URL properties
     * (e.g., click count updates, URL modifications).</p>
     *
     * <p><strong>Performance Impact:</strong> Minimal overhead as version checking
     * is performed at the database level during update operations.</p>
     */
    @Version
    private Long version;

    /**
     * Utility method to check if the entity represents an empty or invalid URL.
     *
     * <p>This convenience method provides a quick way to validate whether the entity
     * contains meaningful URL data. It checks if the original URL field is null,
     * empty, or contains only whitespace characters.</p>
     *
     * <p><strong>Use Cases:</strong></p>
     * <ul>
     *   <li>Pre-save validation in service layers</li>
     *   <li>Data integrity checks during bulk operations</li>
     *   <li>Cleanup operations to identify invalid records</li>
     *   <li>API response filtering to exclude empty entities</li>
     * </ul>
     *
     * <p><strong>Implementation Note:</strong> Only validates the originalUrl field
     * as it's the minimum required data for a meaningful URL entity. Other fields
     * like alias may be null initially and populated later by the service layer.</p>
     *
     * @return {@code true} if the entity is considered empty (original URL is null,
     *         empty, or whitespace-only), {@code false} if it contains valid URL data
     */
    public boolean isEmpty() {
        return (originalUrl == null || originalUrl.trim().isEmpty());
    }
}
